[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_errors = "Gp3jcr7dqCcgp3QbQdcwjS5p5n5usRLoxesQuNaHm4GD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ikrk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
